import { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    // Navbar
    home: "Home", community: "Community", map: "Map", dashboard: "Dashboard",
    adminPanel: "Admin Panel", login: "Login", register: "Register", logout: "Logout",
    // Home hero
    heroTag: "National Flood Early-Warning Network",
    heroTitle1: "Know the risk", heroTitle2: "before the water rises.",
    heroDesc: "The Flood Disaster Management System predicts flood risk for Pakistani cities using machine learning trained on two decades of weather data, explains every prediction in plain terms, and coordinates the people who respond.",
    createAccount: "Create an account", signIn: "Sign in",
    liveFromDeployment: "Live from this deployment", sheltersRegistered: "shelters registered", hospitalsRegistered: "hospitals registered",
    howRiskClassified: "How risk is classified", threeLevels: "Three levels, explained plainly",
    lowRisk: "Low risk", mediumRisk: "Medium risk", highRisk: "High risk",
    lowRiskDesc: "Conditions are within normal range for the season. Standard awareness is enough.",
    mediumRiskDesc: "Elevated rainfall or river conditions. Monitor updates and prepare an evacuation plan.",
    highRiskDesc: "Conditions match historical flood patterns closely. Immediate caution and readiness advised.",
    whatSystemDoes: "What the system does", builtForResponse: "Built for the full response cycle",
    checkCityRisk: "Check your city's flood risk",
    checkCityRiskDesc: "Sign in to run a prediction, see the SHAP explanation behind it, and follow live alerts for your area.",
    goToDashboard: "Go to dashboard",
    // Footer
    emergencyContacts: "Emergency contacts", navigate: "Navigate",
    footerDisclaimer: "This platform is not a substitute for official emergency services. In a real emergency, call 1122.",
    footerTagline: "An AI-assisted flood risk prediction and disaster coordination platform for Pakistan.",
    // Citizen Dashboard
    citizenPortal: "Citizen Portal", checkAreaRisk: "Check your area's flood risk",
    checkAreaRiskDesc: "Enter a few local conditions and get an instant, explained risk assessment for your city.",
    location: "Location", rainfall: "Rainfall (mm)", riverLevel: "River level", temperature: "Temperature (°C)",
    checkFloodRisk: "Check flood risk", analysing: "Analysing…",
    riskLevel: "Risk Level", confidence: "Confidence", riskAnalysis: "Risk analysis",
    safetyRecommendations: "Safety recommendations", modelUsed: "Model used",
    yourHistory: "Your history", riskTrend: "Risk trend over your last checks",
    inEmergency: "In an emergency", findNearestHelp: "Find the nearest help", useMyLocation: "Use my location",
    recentAlerts: "Recent alerts in your area", nearby: "Nearby",
    // Auth pages
    welcomeBack: "Welcome Back", createYourAccount: "Create Account",
    emailAddress: "Email address", password: "Password", fullName: "Full name",
    dontHaveAccount: "Don't have an account?", alreadyHaveAccount: "Already have an account?",
    forgotPassword: "Forgot Password?",
    // Community
    communityHub: "Community Engagement Hub", submitReport: "Submit Incident Report",
    reportTimeline: "Report Timeline", trackingId: "Tracking ID",
    // Home slides
    slide1Tag: "Risk prediction", slide1Title: "See flood risk before it becomes an emergency",
    slide1Desc: "A model trained on two decades of weather data across 10 Pakistani cities classifies your area as Low, Medium or High risk in seconds.",
    slide2Tag: "Explainable AI", slide2Title: "Every prediction shows its reasoning",
    slide2Desc: "A SHAP breakdown lists the exact factors — rainfall, soil moisture, season — that pushed your risk up or down. No black box.",
    slide3Tag: "Rescue coordination", slide3Title: "From alert to action, tracked end to end",
    slide3Desc: "Rescue teams create, assign and update operations by location and priority. Every step is logged from dispatch to completion.",
    slide4Tag: "Community reporting", slide4Title: "Citizens on the ground, officials in the loop",
    slide4Desc: "Anyone can report an incident with a photo and location. Officials review, act, and resolve — visible to the whole community.",
    // Home capabilities
    cap1Title: "Risk Prediction", cap1Desc: "Rainfall, temperature and seasonal patterns classified into a live risk level for your city.",
    cap2Title: "Explainable Results", cap2Desc: "SHAP-powered transparency — see exactly which factors drove each prediction.",
    cap3Title: "Alerting", cap3Desc: "Medium and High risk predictions can trigger alerts, reviewable by administrators.",
    cap4Title: "Rescue Coordination", cap4Desc: "Operations created, assigned and tracked by location and priority.",
    cap5Title: "Community Reporting", cap5Desc: "Citizens report incidents with photos; officials review and resolve.",
    cap6Title: "Shelters & Hospitals", cap6Desc: "A maintained directory of relief camps and hospitals, kept current by administrators.",
    // Community page
    communityTag: "Community Engagement Hub", communityTitle1: "Flood Management", communityTitle2: "Community",
    communityDesc: "Our community engagement platform empowers citizens to report flood incidents, track their status in real-time, and access expert resources.",
    systemStatus: "System Status", activeIncidents: "Active Incidents", monitoredRegions: "Monitored Regions", statusLabel: "Status", live: "Live",
    reportIncident: "Report Incident", submitFloodReport: "Submit Flood Report",
    submitFloodReportDesc: "Help authorities respond faster by reporting from your area. Your report gets tracked in real-time.",
    loginRequired: "Login Required", loginRequiredDesc: "Create a citizen account to submit verified incident reports.",
    loginOrRegister: "Login or Register",
    locationAndType: "Location & Type", incidentType: "Incident Type",
    details: "Details", description: "Description",
    assessmentContact: "Assessment & Contact", severityLevel: "Severity Level", contactInfo: "Contact Information",
    visualEvidence: "Visual Evidence", submitIncidentReport: "Submit incident report",
    liveMap: "Live Map", incidentOverview: "Incident overview",
    reviewPanel: "Review Panel",
    // Map page
    mapTag: "Live Map", mapTitle: "Shelters, hospitals & active response",
    mapDesc: "Every shelter, hospital, rescue operation, community report and blocked road registered in the system, color-coded and searchable.",
    mapDescOfficial: "As an official, you can mark roads as blocked.",
    mapDescCitizen: "Sign in as an official to edit map markers.",
    // Profile
    profileManagement: "Profile Management", viewEditAccount: "View and edit your account information",
    fullName2: "Full Name", emailAddress2: "Email Address", role: "Role", memberSince: "Member since",
    editProfile: "Edit profile", saveChanges: "Save Changes", saving: "Saving…", cancel: "Cancel",
    roleCannotChange: "Role cannot be changed. Contact administrator if needed.",
    accountInfo: "Account information", accountStatus: "Account Status", active: "Active", dashboardAccess: "Dashboard Access",
    citizenDashboardLabel: "Citizen Dashboard", rescueDashboardLabel: "Rescue Dashboard",
    govDashboardLabel: "Government Dashboard", adminDashboardLabel: "Admin Dashboard",
    // Forgot Password
    resetPassword: "Reset password", enterEmailForCode: "Enter your email to receive a verification code",
    enterCodeAndPassword: "Enter the code and choose a new password",
    sendCode: "Send verification code", sending: "Sending…",
    verificationCode: "Verification code", newPassword: "New password", confirmNewPassword: "Confirm new password",
    resettingPassword: "Resetting…", useAnotherEmail: "← Use a different email", backToLogin: "← Back to login",
    smtpNote: "No SMTP service is configured for this deployment — the code is printed to the backend terminal instead of a real inbox. The reset itself is fully functional.",
    // Admin Dashboard
    administration: "Administration", controlPanel: "Control panel",
    controlPanelDesc: "Manage users, alerts, shelters, hospitals and review flood predictions.",
    totalUsers: "Total users", citizens: "Citizens", rescueWorkers: "Rescue workers", govOfficials: "Gov officials", admins: "Admins",
    userManagement: "User management", userManagementDesc: "Manage system users, roles, and account status.",
    newUser: "+ New user", newAlert: "+ New alert",
    name: "Name", email: "Email", status: "Status", actions: "Actions",
    alertsLog: "Alerts Log", floodPredictions: "Flood Risk Predictions", export: "Export",
    allRiskLevels: "All Risk Levels", shelters: "Shelters", hospitals: "Hospitals",
    addShelter: "+ Add Shelter", addHospital: "+ Add Hospital", systemEventLog: "System event log",
    viewLog: "View log", hideLog: "Hide log", maintainability: "Maintainability",
    retrainModel: "Retrain the flood risk model", mlBackend: "ML Backend",
    // Rescue Dashboard
    rescueCoordination: "Rescue Coordination", operationsCenter: "Operations center",
    operationsCenterDesc: "Monitor active alerts and coordinate emergency response teams.",
    rescueOperations: "Rescue Operations", newOperation: "+ New Operation",
    location2: "Location", riskLevel2: "Risk Level", assignWorker: "Assign Rescue Worker",
    createNotify: "Create & Notify Team", unassigned: "Unassigned", markComplete: "Mark Complete", start: "Start",
    teamLabel: "Team", updatedLabel: "Updated",
    activeOpsBlockedRoads: "Active operations & blocked roads",
    // Government Dashboard
    govOversight: "Government Oversight", analyticsDashboard: "Analytics dashboard",
    analyticsDashboardDesc: "Comprehensive flood risk analysis across monitored regions.",
    filters: "Filters", riskDistribution: "Risk Distribution", confidenceTrend: "Confidence Trend",
    topRiskLocations: "Top Risk Locations", riskOverview: "Risk Overview", predictionHistory: "Prediction History",
    // Footer (full)
    footerTaglineFull: "An AI-assisted flood risk prediction and disaster coordination platform for Pakistan — combining machine learning, explainable predictions, and real-time coordination between citizens, rescue teams, and officials.",
    communityReportsLink: "Community reports", liveMapLink: "Live map", systemLive: "System live",
    // Community page (more)
    reportTimelineTitle: "Report Timeline", noReportsYet: "No reports yet.",
    yourReports: "Your reports", allReports: "All community reports",
    trackStatusDesc: "Track the status of your submitted reports.",
    filterBySeverity: "Severity", filterByStatus: "Status", filterByRegion: "Region", all: "All",
    submitted: "Submitted", underReview: "Under Review", actionTaken: "Action Taken", resolved: "Resolved",
    lowSeverity: "Low", mediumSeverity: "Medium", highSeverity: "High",
    markUnderReview: "Mark Under Review", markActionTaken: "Mark Action Taken", markResolved: "Mark Resolved",
    peopleConfirmed: "people have confirmed this", personConfirmed: "person has confirmed this",
    iSeeThisToo: "I see this too", confirmed: "Confirmed",
    // Map filters/search (shared FloodMap component)
    searchPlaceholder: "Search shelters, hospitals, locations…",
    filterShelters: "Shelters", filterHospitals: "Hospitals", filterRescueOps: "Rescue operations",
    filterCommunityReports: "Community reports", filterBlockedRoads: "Blocked roads",
    markBlockedRoad: "+ Mark blocked road", clickMapToPlace: "Click the map to place…",
    routeToNearest: "Route to nearest shelter", findingRoute: "Finding route…",
    loadingMapData: "Loading map data…", noOperationsFound: "No rescue operations yet.",
    // Admin - Shelters/Hospitals forms
    shelterName: "Shelter name", address: "Address", capacity: "Capacity", contact: "Contact number",
    saveShelter: "Save Shelter", hospitalName: "Hospital name", availableServices: "Available services",
    saveHospital: "Save Hospital", delete: "Delete", noSheltersRegistered: "No shelters registered yet.",
    noHospitalsRegistered: "No hospitals registered yet.", searchByNameAddress: "Search by name or address…",
    realTimeTracking: "Real-Time Tracking", trackingIdLabel: "Tracking ID",
    submitReportToTrack: "Submit a report or select one from the map to see the tracking timeline.",
    stepSubmittedDesc: "Submitted and queued for review", stepReviewDesc: "Review team evaluating impact",
    stepActionDesc: "Authorities executing response", stepResolvedDesc: "Issue resolved and documented",
    officialReviewWorkspace: "Official review workspace",
    filterReportsDesc: "Filter incident reports by status, region or severity and take action.",
    allSeverity: "All Severity", allStatus: "All Status", allRegions: "All Regions",
    colTrackingId: "Tracking ID", colLocation: "Location", colSeverity: "Severity", colStatus: "Status",
    colSubmittedBy: "Submitted By", colAction: "Action",
    reviewAction: "Review", actionAction: "Action", resolveAction: "Resolve",
    view: "View", deactivate: "Deactivate", activate: "Activate", inactive: "Inactive",
    // CitizenDashboard extras
    assessmentResult: "Assessment result", humidityPct: "Humidity (%)", matchedTo: "Matched to",
    modelInputsUsed: "Model inputs used", noRegisteredHospitals: "No registered hospitals found.",
    noRegisteredShelters: "No registered shelters found.", surfaceSoilMoisture: "Surface soil moisture",
    whyThisPrediction: "Why this prediction?", windSpeedMs: "Wind speed (m/s)",
    fetchingWeather: "Fetching live weather for this city…",
    weatherFetchFailed: "Couldn't fetch weather for that location (check the spelling) — enter rainfall & temperature manually.",
    riverLevelHint: "Recorded for reference — pick what you can see, no exact measurement needed.",
    showAdvanced: "+ Show advanced weather inputs (humidity, wind, soil moisture)",
    hideAdvanced: "− Hide advanced weather inputs (humidity, wind, soil moisture)",
    modelAttributesNote: "The model uses 20 trained attributes. Once you pick your city, humidity, wind and soil moisture are fetched automatically from live weather data — there's nothing else for you to enter.",
    shapBreakdownNote: "SHAP breakdown — positive bars pushed the risk up, negative bars pulled it down.",
    modelInputsNote: "All attributes the model was actually trained on and fed for this prediction (plus the city, shown above).",
    basedOnTypedCity: "Based on the city you entered", basedOnDeviceLocation: "Based on your device's current location",
    kmAway: "km away", capacityLabel: "capacity", viewOnMap: "View on map →",
    couldntGetLocation: "Couldn't get your location. Check your browser's location permission and try again.",
    findingNearby: "Finding nearby shelters & hospitals…", leaveBlankAvg: "Leave blank for city average",
    selectYourCity: "Select your city", cityCoverageNote: "Covering 53 major cities across Pakistan.",
    selectRainfallLevel: "Select what you're seeing outside",
    rainfallNone: "No rain", rainfallLight: "Light drizzle", rainfallModerate: "Moderate rain",
    rainfallHeavy: "Heavy rain", rainfallVeryHeavy: "Very heavy / continuous rain",
    actualDetected: "Actual detected", rainfallHint: "Just pick what matches what you can see outside — no exact measurement needed.",
    leaveBlankAvg2: "Not sure — use city average", humidityDry: "Dry / comfortable", humidityNormal: "Normal",
    humidityHumid: "Humid / sticky", humidityVeryHumid: "Very humid",
    windCalm: "Calm — little to no wind", windBreezy: "Breezy", windStrong: "Strong wind",
    soilMoistureRemovedNote: "Soil moisture isn't something you can judge by eye, so we always estimate it from historical data for your city and season.",
    locationRequired: "Please select your city", rainfallRequired: "Please select a rainfall level",
    rainfallPositive: "Rainfall must be a positive number", rainfallUnrealistic: "Rainfall value seems unrealistic (too high)",
    temperatureRequired: "Temperature is required", temperatureMustBeNumber: "Temperature must be a number",
    temperatureRange: "Temperature must be between -10°C and 60°C", invalidEmailFormat: "Please enter a valid email address",
    fillRequiredFields: "Please complete all required fields before submitting.",
    locationTooShort: "Please enter a more specific location (at least 3 characters).",
    descriptionTooShort: "Please describe the incident in a bit more detail (at least 10 characters).",
    invalidPhoneFormat: "Please enter a valid Pakistani phone number (e.g. 03001234567).",
    incidentReportSubmitted: "Incident Report Submitted Successfully", couldNotSubmitReport: "Could not submit report. Please try again.",
    capacityMustBePositive: "Capacity must be a positive number", passwordTooShort: "Password must be at least 6 characters",
    predictionFailedGeneric: "Failed to get prediction. Please check the backend server is running and try again.",
    floodRiskAnalysisCompleted: "Flood risk analysis completed!",
    liveConditionsDetected: "Live conditions detected for your city",
    soil7dayAvgLabel: "7-day soil avg",
    policyPlanning: "Policy planning", resourceGapAnalysis: "Resource gap analysis",
    resourceGapDesc: "Cities currently at Medium/High risk with 3 or fewer combined shelters/hospitals (below the network average) are flagged as under-resourced.",
    underResourced: "Under-resourced",
    comparativeAnalysis: "Comparative analysis", multiCityComparison: "Multi-city comparison",
    selectCityToCompare: "Select a city to compare", latestRisk: "Latest risk", highRiskCount: "High-risk predictions",
    reporting: "Reporting", districtReport: "District report",
    districtReportDesc: "Download an official PDF summary of a city's recent flood-risk history and resource coverage.",
    downloadReport: "Download report",
    officialCommunication: "Official communication", publicAdvisories: "Public advisories",
    advisoriesDesc: "Policy-level public guidance, distinct from emergency alerts — e.g. seasonal preparedness notices.",
    issueAdvisory: "+ Issue advisory", advisoryTitlePh: "Advisory title", advisoryMessagePh: "Advisory message",
    advisoryRegionPh: "Region (e.g. Sindh, or leave as 'All regions')", noAdvisoriesYet: "No advisories issued yet.",
    withdraw: "Withdraw", confirmWithdrawAdvisory: "Withdraw this advisory? It will no longer be shown to the public.",
    reportGenerationFailed: "Could not generate the report. Make sure the backend has fpdf2 installed.",
    emergencyResponse: "Emergency response", highRiskAlerts: "High-risk alerts",
    highRiskAlertsDesc: "Active Medium/High risk alerts — assign a rescue worker to dispatch a response operation.",
    noActiveAlerts: "No active Medium/High risk alerts right now.",
    assignRescueWorker: "Assign rescue worker", selectRescueWorker: "Select a rescue worker",
    operationNotesPh: "Operation notes (optional)", confirmAssignment: "Confirm assignment",
    operationAssignedMsg: "Rescue worker assigned — operation created.",
    workforceOversight: "Workforce oversight", rescueWorkerDirectory: "Rescue worker directory",
    rescueWorkerDirectoryDesc: "All registered rescue workers — manage their active status here.",
    noRescueWorkersYet: "No rescue workers registered yet.", assignedTo: "Assigned to",
    operationsMonitoring: "Operations monitoring", rescueOperationsOverview: "Rescue operations overview",
    rescueOperationsOverviewDesc: "Live status of all rescue operations currently underway or completed, across every district.",
    donationPledgesOverviewDesc: "Resource pledges currently offered by donors and organisations, for coordination and planning.",
    historicalContext: "Historical context", seasonalTrend: "Seasonal / historical trend",
    seasonalTrendDesc: "Real prediction history grouped by month — how flood risk has actually trended over recent months.",
    escalationLog: "Emergency escalation log",
    escalationLogDesc: "A record of rescue worker assignments made from alerts, for accountability — advisories are tracked separately below.",
    tabAnalytics: "Analytics", tabEmergencyResponse: "Emergency Response", tabPolicyPlanning: "Policy & Planning", tabCommunication: "Communication",
    tabMyOperations: "My Operations", tabTeamOverview: "Team Overview", tabMapNavigation: "Map & Navigation",
    onDuty: "On Duty", offDuty: "Off Duty", myPerformance: "My performance", myStatsTitle: "My statistics",
    activeLabel: "Active", myAssignedOperations: "My assigned operations",
    myAssignedOperationsDesc: "Operations currently assigned to you specifically.",
    noOperationsAssignedToMe: "No operations assigned to you right now.",
    backupNeeded: "Backup requested", getRoute: "Get route", requestBackup: "Request backup",
    addUpdateNotePh: "Add a quick update (e.g. 'en route', 'arrived')…", post: "Post",
    backupRequestedMsg: "Backup requested — flagged for coordinators.",
    locationNotResolvable: "Couldn't resolve this location's coordinates for directions.",
    tabTeamResources: "Team & Resources", coordination: "Coordination",
    onDutyWorkersTitle: "Who's on duty right now", onDutyWorkersDesc: "Rescue workers currently marked as available.",
    noOneOnDuty: "No one is currently marked on-duty.",
    teamRosterTitle: "Team roster",
    equipmentTrackerTitle: "Equipment & resources", equipmentTrackerDesc: "Assign equipment to an active operation, or tap the status pill to mark it available/in use.",
    statusAvailable: "Available", statusInUse: "In use",
    addEquipmentBtn: "Add equipment", equipmentNamePh: "e.g. Life Jackets", quantityLabel: "Quantity",
    unassignedEquipment: "Not assigned to an operation", assignedToLabel: "Deployed to",
    availableOfTotal: "available", freeUpBtn: "Free up this unit", selectOperationPh: "Select an operation…",
    qtyShort: "Qty", deployBtn: "Deploy", noActiveOpsHint: "No active operations to deploy to right now.",
    continuity: "Continuity", shiftHandoverTitle: "Shift handover notes",
    shiftHandoverDesc: "Leave a note for whoever picks up next — ongoing situations, things to watch.",
    handoverNotePh: "e.g. 'Sector 4 still flooding, keep an eye on it'…", noHandoverNotesYet: "No handover notes yet.",
    priorityNormal: "Normal", priorityWatch: "Watch", priorityUrgent: "Urgent",
    markNoteResolved: "Mark resolved", reopenNote: "Reopen",
    rescueTeamsTitle: "Rescue teams", rescueTeamsDesc: "Group workers into a full team (3-4 people) so a flooded area gets a real response crew, not just one name.",
    newTeamBtn: "New team", teamNameLabel: "Team name", teamNamePh: "e.g. Team Alpha",
    teamMembersLabel: "Team members", teamNeedsTwoHint: "Select at least 2 members to form a team.",
    createTeamBtn: "Create team", noTeamsYet: "No rescue teams yet — create one to assign a full crew to an operation.",
    noTeamsYetHint: "No teams yet — create one in Team Roster below, or assign an individual for now.",
    deleteTeam: "Remove", membersLabel: "members",
    assignModeTeam: "Assign a team", assignModeIndividual: "Assign one person",
    communityReportsHeading: "Community Reports", reportedByLabel: "Reported by",
    linkedOperationLabel: "Linked operation", dispatchTeamBtn: "Dispatch team",
    reportDispatchedMsg: "Report dispatched — a rescue operation has been created.",
    volunteersTitle: "Volunteers", volunteersDesc: "People who signed up on the Community page's \"Get Involved\" form — assign one to a nearby operation when extra hands are needed.",
    noVolunteersYet: "No volunteers registered yet.", assignToOperationDropdown: "Assign to an operation…",
    recordKeeping: "Record keeping", historicalSearchTitle: "Historical operations",
    historicalSearchDesc: "Search past completed operations by location, team, or notes.",
    historicalSearchPh: "Search by location, team, or notes…", noHistoricalResults: "No completed operations match your search.",
    showingXofYPredictions: "Showing {x} of {y} predictions", showingFirst20: "Showing first 20 results. Use filters to see more data.",
    liveConditionsNote: "Fetched automatically from live weather data — nothing to fill in here.",
    egLahore: "e.g. Lahore", enterCityToAutofill: "Enter your city above to auto-fill, or type it in",
    // AdminDashboard extras
    alertMessage: "Alert Message", alertStatistics: "Alert Statistics", cancelled: "Cancelled",
    close: "Close", createAlertBtn: "Create Alert", createNewUserBtn: "Create New User",
    highRiskAlerts: "High Risk Alerts", loadingAdminData: "Loading admin data...",
    noEventsLogged: "No events logged yet.", noPredictionsMatch: "No predictions match these filters.",
    passwordLabel: "Password", rainfallLabel: "Rainfall", registeredAccounts: "Registered accounts",
    reviewUserNote: "Review this user and update status from the control panel.",
    riskLevelLabel: "Risk Level", riskAssessmentsMade: "Risk assessments made", riskLabel: "Risk",
    riverLevelLabel: "River Level", roleLabel: "Role", sheltersHospitalsBlockedRoads: "Shelters, hospitals & blocked roads",
    systemReports: "System Reports", systemAlertsGenerated: "System alerts generated", timestamp: "Timestamp",
    totalAlerts: "Total Alerts", totalPredictionsLabel: "Total Predictions", totalUsersLabel: "Total Users",
    userDistribution: "User Distribution", userDetails: "User details",
    enterAlertMessage: "Enter alert message", enterEmail: "Enter email", enterLocation: "Enter location",
    enterName: "Enter name", enterPassword: "Enter password", searchByNameEmailRole: "Search by name, email or role…",
    // RescueDashboard extras
    alertDetails: "Alert Details", emergencyStatus: "Emergency Status", highRiskAreas: "High Risk Areas",
    noHighRiskAreas: "No high risk areas detected", noMediumRiskAreas: "No medium risk areas detected",
    whatNeedsToHappen: "What needs to happen here?", egSukkur: "e.g. Sukkur",
    // GovDashboard extras
    allLocations: "All Locations", allTime: "All Time", dateRange: "Date Range", dateLabel: "Date",
    lastMonth: "Last Month", lastWeek: "Last Week", loadingAnalytics: "Loading analytics data...", todayLabel: "Today",
    // Community extras
    dragDropImage: "Drag & drop image here", loginToSubmit: "Login to Submit", removeLabel: "Remove",
    cityRegionNeighbourhood: "City, region or neighbourhood",
    // Register/Login extras
    confirmPasswordLabel: "Confirm Password", joinPlatform: "Join the platform to stay informed",
    whoAreYou: "Who are you?", confirmYourPassword: "Confirm your password", createPasswordPh: "Create a password",
    enterYourEmail: "Enter your email", enterYourFullName: "Enter your full name",
    rememberMe: "Remember me", enterYourPassword: "Enter your password",
    citizenSingular: "Citizen", rescueWorkerSingular: "Rescue Worker",
    normalNoThreats: "NORMAL - No Immediate Threats", orClickToBrowse: "or click to browse",
    incidentFlooding: "Flooding", incidentLandslide: "Landslide", incidentRoadBlockage: "Road Blockage",
    incidentWaterContamination: "Water Contamination", incidentInfraDamage: "Infrastructure Damage",
    incidentEvacuation: "Evacuation Required",
    recentAlertsTitle: "Recent alerts", noAlertsYet: "No alerts yet.", noRecordedHistory: "No recorded history yet",
    // Forecast
    forecastTitle: "3-day risk outlook", getForecast: "Get forecast", forecastError: "Couldn't fetch the forecast — try again shortly.",
    forecastHint: "See how risk is expected to change over the next 3 days for", yourCity: "your city", loadingEllipsis: "Loading…",
    // Model comparison
    modelComparisonTitle: "Model comparison", modelsAgree: "Both models agree on this prediction.",
    modelsDisagree: "These models disagree — treat with extra caution and check the SHAP breakdown above.",
    // Family contacts
    safetyNetwork: "Safety network", familyContactsTitle: "Family & emergency contacts", addContact: "+ Add contact",
    familyContactsDesc: "Add people you'd want kept in the loop. When a High-risk alert is issued for your area, you can notify them all in one tap (no SMS service is configured for this deployment, so notifications are logged rather than actually sent).",
    namePh: "Name", phonePh: "Phone", relationPh: "Relation (e.g. Sister)", saveContact: "Save contact",
    noContactsYet: "No contacts added yet.", removeContact: "Remove", notifyAllContacts: "Notify all contacts now",
    downloadPdfBtn: "Download PDF",
    // Admin accuracy/confidence
    modelAccuracyOverTime: "Model accuracy over time",
    noRetrainEvents: "No retrain events yet — accuracy is recorded here each time the model is retrained (see above).",
    predictionConfidenceTrend: "Prediction confidence trend", notEnoughHistory: "Not enough prediction history yet to chart a trend.",
    // Admin volunteers/donations
    registeredVolunteers: "Registered volunteers", noVolunteersYet: "No volunteers registered yet. Citizens can register from the Community page.",
    phoneCol: "Phone", cityCol: "City", skillsCol: "Skills", resourceCoordination: "Resource coordination",
    donationPledges: "Donation pledges", noDonationsYet: "No donations pledged yet.",
    // Admin QR
    checkInQr: "Check-in QR", hideQr: "Hide QR", qrInstructions: "Print or display this at the shelter entrance. Arrivals scan it to check in.",
    // Admin download reports
    downloadUsersReport: "Download Users Report", downloadAlertsReport: "Download Alerts Report", downloadPredictionsReport: "Download Predictions Report",
    // Community volunteer/donation forms
    getInvolved: "Get involved", registerVolunteerTitle: "Register as a volunteer",
    registerVolunteerDesc: "Rescue teams can reach out to you when help is needed nearby.", registerAsVolunteerBtn: "Register as volunteer",
    supportReliefEfforts: "Support relief efforts", pledgeDonationTitle: "Pledge a donation",
    pledgeDonationDesc: "Supplies, funds or equipment — let coordinators know what you can offer.", pledgeDonationBtn: "Pledge donation",
    fullNamePh: "Full name", phoneNumberPh: "Phone number", yourCityPh: "Your city",
    skillsExamplePh: "Skills (e.g. First Aid, Driving, Swimming)", nameOrgPh: "Your name / organisation",
    contactNumberPh: "Contact number", itemExamplePh: "Item (e.g. Blankets)",
    thankYouVolunteer: "Thank you for registering — rescue teams can now see you.",
    thankYouDonation: "Thank you — your pledge has been recorded.",
    // Home historical floods
    whyMatters: "Why this matters", recentFloodsTitle: "Pakistan's recent major floods",
    flood2010Title: "Indus River floods",
    flood2010Desc: "One of the most severe floods in Pakistan's history, affecting roughly a fifth of the country's total land area and displacing millions along the Indus basin.",
    flood2011Title: "Sindh floods",
    flood2011Desc: "Heavy monsoon rains caused widespread flooding across Sindh a year after the 2010 disaster, again displacing large rural populations.",
    flood2022Title: "Monsoon 'super floods'",
    flood2022Desc: "Record monsoon rainfall combined with glacial melt caused catastrophic flooding across Sindh, Balochistan and southern Punjab, one of the costliest disasters in the country's history.",
    floodsFootnote: "Figures are general historical context, not live statistics. Early prediction and coordination — what this platform focuses on — is one of the most effective ways to reduce the impact of events like these.",
    // CheckIn page
    shelterCheckin: "Shelter Check-in", youveArrived: "You've arrived",
    checkedInSuccess: "Checked in successfully. Stay safe — help is coordinated from here.",
    tellUsName: "Optionally tell us your name so responders know who's arrived.", yourNamePh: "Your name (optional)",
    checkingIn: "Checking in…", checkInBtn: "Check in", checkInError: "Something went wrong — please tell shelter staff directly.",
    myReports: "My reports", myReportsDesc: "Select a report to view its tracking timeline.",
    noReportsSubmitted: "You haven't submitted any reports yet.", submittedOn: "Submitted",
    assignTeamPrompt: "Assign a rescue team to this operation (optional, you can leave this blank):",
    rescueOpCreatedMsg: "Action taken — Rescue Operation created", reportSetTo: "Report set to",
    peopleRescuedPrompt: "How many people were rescued? (enter a number)",
    resourcesUsedPrompt: "What resources were used? (e.g. 2 boats, medical kits)",
    completionNotesPrompt: "Any completion notes?",
    operationMarkedAs: "Operation marked as", couldNotUpdateOp: "Could not update operation status.",
    completedIn: "Completed in", peopleRescuedLabel: "People rescued", resourcesUsedLabel: "Resources used",
    nearestShelter: "Nearest shelter", nearestHospital: "Nearest hospital", assignVolunteerLabel: "+ Assign a volunteer",
    rescueStatsLabel: "Rescue statistics", operationsOverviewLabel: "Operations overview",
    totalOperationsLabel: "Total operations", completedLabel: "Completed", avgMinutesLabel: "Avg. completion (min)",
    completionReportTitle: "Completion report", completionReportDesc: "Log what happened before marking this operation complete — this is saved with the operation permanently.",
    resourcesUsedPlaceholder: "e.g. 2 boats, medical kits", completionNotesLabel: "Notes",
    completionNotesPlaceholder: "e.g. All families evacuated safely", submitAndComplete: "Submit & mark complete",
    // Safety tips
    tipEvacuate: "Evacuate to higher ground immediately", tipFollowAuthorities: "Follow emergency instructions from authorities",
    tipEmergencyKit: "Keep emergency kit ready with essentials", tipOfficialChannels: "Stay informed through official channels",
    tipMonitorWeather: "Monitor weather updates regularly", tipPrepareSupplies: "Prepare emergency supplies",
    tipKnowRoutes: "Know evacuation routes in your area", tipStayAlert: "Stay alert for further warnings",
    tipNormalActivities: "Continue normal activities with awareness", tipBasicSupplies: "Keep basic emergency supplies",
    tipWeatherConditions: "Stay informed about weather conditions", tipFamilyComm: "Maintain communication with family",
    tipStayInformed: "Stay informed and be prepared",
    // Weather status / find help / retrain
    weatherAutoFilled: "Rainfall & temperature filled in from live weather data", autoFilledEditable: "auto-filled, editable",
    findHelpNear: "Find help near", retrainDescription: "Upload a new historical dataset (CSV) to retrain the model. It must include a flood_label column and either a city column or the existing attribute columns. The retrained model is evaluated on a held-out split and only deployed automatically if it reaches the 80% minimum accuracy required by FR10-04 — otherwise it's discarded and the current model keeps running.",
    serviceEmergency: "Emergency",
    statusPrefix: "Status", riskPrefix: "Risk", severityPrefix: "Severity",
    statusAssigned: "Assigned", statusInProgress: "In Progress", statusCompleted: "Completed",
    statusBlocked: "Blocked", statusCleared: "Cleared", markAsCleared: "Mark as cleared",
    floodRiskAnalysisFor: "Flood risk analysis for", matchedCityLabel: "matched city",
    inputParameters: "Input parameters", riverLevelNote: "recorded, not used by the model — no river-level data in training set",
    mlModelPrediction: "ML model prediction", floodRiskWord: "flood risk", modelConfidenceLabel: "Model confidence",
    riskAssessmentLabel: "Risk assessment", generatedUsingModel: "Generated using a", modelTrainedOnData: "model trained on 10-city, 24-year historical flood data.",
    riskSummaryHigh: "Critical flood risk detected. Immediate evacuation and emergency measures required.",
    riskSummaryMedium: "Moderate flood risk. Stay alert and monitor conditions closely.",
    riskSummaryLow: "Low flood risk. Conditions appear safe but remain vigilant.",
    featTemperature: "Temperature", featHumidity: "Humidity", featWindSpeed: "Wind speed",
    featSoilMoistureTop: "Surface soil moisture", featSoil7dayAvg: "7-day soil moisture average",
    featMonth: "Month", featYear: "Year", featIsMonsoon: "Monsoon season", featSeason: "Season",
    featRainIntensity: "Rainfall intensity", featCityPrefix: "City",
    enterRegisteredEmail: "Enter your registered email", checkBackendTerminal: "Check the backend terminal",
    createNewPasswordPh: "Create a new password", repeatNewPassword: "Repeat the new password",
    enterFullNamePh: "Enter your full name", enterEmailAddressPh: "Enter your email address",
    loadingDots: "Loading...", brandName: "Flood Disaster Management System",
    exportCsv: "Export report (CSV)", criticalAlertsHeading: "Critical alerts — immediate action required",
    rescueOpsSubtitle: "Create, assign and track rescue operations — sorted by risk priority.",
    areasWord: "Areas",
    rescue1122: "Rescue 1122", pdmaHelpline: "PDMA Punjab Helpline",
    loginRequiredFull: "To submit verified flood incident reports that help authorities coordinate rapid response, please login with your citizen account.",
    incidentOverviewDesc: "Community reports plotted alongside shelters, hospitals and active rescue operations.",
    exportCsv: "Export report (CSV)", rescueOpsSubtitle: "Create, assign and track rescue operations — sorted by risk priority.",
    riverLevelNormal: "Normal — within its usual banks", riverLevelRising: "Rising — noticeably higher than usual",
    riverLevelOverflowing: "Overflowing — water beyond the banks", riverLevelNotSure: "Not sure / prefer not to say",
    lowChart: "Low", medChart: "Med", highChart: "High", loginSuccessful: "Login successful! Redirecting...",
    mediumRiskAreas: "Medium Risk Areas", elevatedDetected: "ELEVATED - Medium Risk Areas Detected", criticalMultiple: "CRITICAL - Multiple High Risk Areas",
    loginSuccessRedirect: "Successfully logged in! Redirecting to dashboard...",
  },
  ur: {
    home: "ہوم", community: "کمیونٹی", map: "نقشہ", dashboard: "ڈیش بورڈ",
    adminPanel: "ایڈمن پینل", login: "لاگ ان", register: "رجسٹر", logout: "لاگ آؤٹ",
    heroTag: "قومی سیلاب وارننگ نیٹ ورک",
    heroTitle1: "خطرے کو پہچانیں", heroTitle2: "پانی بڑھنے سے پہلے۔",
    heroDesc: "فلڈ ڈیزاسٹر مینجمنٹ سسٹم مشین لرننگ کے ذریعے پاکستانی شہروں کے لیے سیلاب کے خطرے کی پیش گوئی کرتا ہے، ہر پیشگوئی کی وجہ آسان الفاظ میں بتاتا ہے، اور امدادی کارکنوں کو مربوط کرتا ہے۔",
    createAccount: "اکاؤنٹ بنائیں", signIn: "سائن ان",
    liveFromDeployment: "لائیو ڈیٹا", sheltersRegistered: "شیلٹرز رجسٹرڈ", hospitalsRegistered: "ہسپتال رجسٹرڈ",
    howRiskClassified: "خطرے کی درجہ بندی", threeLevels: "تین درجے، آسان الفاظ میں",
    lowRisk: "کم خطرہ", mediumRisk: "درمیانہ خطرہ", highRisk: "زیادہ خطرہ",
    lowRiskDesc: "حالات موسم کے لحاظ سے معمول کے مطابق ہیں۔ عام آگاہی کافی ہے۔",
    mediumRiskDesc: "بارش یا دریا کی سطح میں اضافہ۔ اپڈیٹس پر نظر رکھیں اور انخلا کا منصوبہ تیار رکھیں۔",
    highRiskDesc: "حالات ماضی کے سیلابی پیٹرن سے قریبی مطابقت رکھتے ہیں۔ فوری احتیاط اور تیاری ضروری ہے۔",
    whatSystemDoes: "سسٹم کیا کرتا ہے", builtForResponse: "مکمل ردعمل کے چکر کے لیے بنایا گیا",
    checkCityRisk: "اپنے شہر کا سیلابی خطرہ چیک کریں",
    checkCityRiskDesc: "پیشگوئی چلانے، SHAP وضاحت دیکھنے اور اپنے علاقے کے لائیو الرٹس دیکھنے کے لیے سائن ان کریں۔",
    goToDashboard: "ڈیش بورڈ پر جائیں",
    emergencyContacts: "ہنگامی رابطے", navigate: "نیویگیشن",
    footerDisclaimer: "یہ پلیٹ فارم سرکاری ہنگامی خدمات کا متبادل نہیں ہے۔ حقیقی ایمرجنسی میں 1122 پر کال کریں۔",
    footerTagline: "پاکستان کے لیے مصنوعی ذہانت پر مبنی سیلابی خطرے کی پیش گوئی اور آفات کوآرڈینیشن پلیٹ فارم۔",
    citizenPortal: "شہری پورٹل", checkAreaRisk: "اپنے علاقے کا سیلابی خطرہ چیک کریں",
    checkAreaRiskDesc: "چند مقامی حالات درج کریں اور اپنے شہر کے لیے فوری، وضاحت شدہ خطرے کا جائزہ حاصل کریں۔",
    location: "مقام", rainfall: "بارش (ملی میٹر)", riverLevel: "دریا کی سطح", temperature: "درجہ حرارت (°C)",
    checkFloodRisk: "سیلابی خطرہ چیک کریں", analysing: "تجزیہ ہو رہا ہے…",
    riskLevel: "خطرے کی سطح", confidence: "اعتماد", riskAnalysis: "خطرے کا تجزیہ",
    safetyRecommendations: "حفاظتی تجاویز", modelUsed: "استعمال شدہ ماڈل",
    yourHistory: "آپ کی تاریخ", riskTrend: "آپ کی حالیہ چیکس میں خطرے کا رجحان",
    inEmergency: "ہنگامی صورتحال میں", findNearestHelp: "قریب ترین مدد تلاش کریں", useMyLocation: "میری لوکیشن استعمال کریں",
    recentAlerts: "آپ کے علاقے میں حالیہ الرٹس", nearby: "قریبی",
    welcomeBack: "خوش آمدید", createYourAccount: "اکاؤنٹ بنائیں",
    emailAddress: "ای میل ایڈریس", password: "پاس ورڈ", fullName: "پورا نام",
    dontHaveAccount: "اکاؤنٹ نہیں ہے؟", alreadyHaveAccount: "پہلے سے اکاؤنٹ ہے؟",
    forgotPassword: "پاس ورڈ بھول گئے؟",
    communityHub: "کمیونٹی انگیجمنٹ ہب", submitReport: "واقعے کی رپورٹ جمع کروائیں",
    reportTimeline: "رپورٹ ٹائم لائن", trackingId: "ٹریکنگ آئی ڈی",
    slide1Tag: "خطرے کی پیشگوئی", slide1Title: "سیلابی خطرہ ایمرجنسی بننے سے پہلے جانیں",
    slide1Desc: "10 پاکستانی شہروں کے دو دہائیوں کے موسمی ڈیٹا پر تربیت یافتہ ماڈل آپ کے علاقے کو سیکنڈوں میں کم، درمیانہ یا زیادہ خطرے میں درجہ بند کرتا ہے۔",
    slide2Tag: "قابل وضاحت AI", slide2Title: "ہر پیشگوئی اپنی وجہ بتاتی ہے",
    slide2Desc: "SHAP تجزیہ بارش، مٹی کی نمی، موسم جیسے عوامل بتاتا ہے جنہوں نے خطرہ بڑھایا یا کم کیا۔ کوئی بلیک باکس نہیں۔",
    slide3Tag: "ریسکیو کوآرڈینیشن", slide3Title: "الرٹ سے عمل تک، مکمل ٹریکنگ",
    slide3Desc: "ریسکیو ٹیمیں مقام اور ترجیح کے مطابق آپریشنز بناتی، تفویض کرتی اور اپڈیٹ کرتی ہیں۔",
    slide4Tag: "کمیونٹی رپورٹنگ", slide4Title: "زمینی شہری، حکام رابطے میں",
    slide4Desc: "کوئی بھی تصویر اور مقام کے ساتھ واقعہ رپورٹ کر سکتا ہے۔ حکام جائزہ لے کر عمل کرتے ہیں۔",
    cap1Title: "خطرے کی پیشگوئی", cap1Desc: "بارش، درجہ حرارت اور موسمی پیٹرن سے آپ کے شہر کا لائیو خطرہ درجہ بند ہوتا ہے۔",
    cap2Title: "قابل وضاحت نتائج", cap2Desc: "SHAP کی مدد سے شفافیت — دیکھیں کہ کون سے عوامل نے ہر پیشگوئی کو متاثر کیا۔",
    cap3Title: "الرٹنگ", cap3Desc: "درمیانہ اور زیادہ خطرے کی پیشگوئیاں الرٹ متحرک کر سکتی ہیں۔",
    cap4Title: "ریسکیو کوآرڈینیشن", cap4Desc: "آپریشنز مقام اور ترجیح کے مطابق بنائے، تفویض اور ٹریک کیے جاتے ہیں۔",
    cap5Title: "کمیونٹی رپورٹنگ", cap5Desc: "شہری تصاویر کے ساتھ واقعات رپورٹ کرتے ہیں؛ حکام جائزہ لے کر حل کرتے ہیں۔",
    cap6Title: "شیلٹرز اور ہسپتال", cap6Desc: "امدادی کیمپوں اور ہسپتالوں کی فہرست، منتظمین کی جانب سے تازہ ترین۔",
    communityTag: "کمیونٹی انگیجمنٹ ہب", communityTitle1: "فلڈ مینجمنٹ", communityTitle2: "کمیونٹی",
    communityDesc: "ہمارا کمیونٹی پلیٹ فارم شہریوں کو سیلابی واقعات رپورٹ کرنے، ان کی حیثیت ٹریک کرنے اور ماہرانہ وسائل تک رسائی کی سہولت دیتا ہے۔",
    systemStatus: "سسٹم کی حیثیت", activeIncidents: "فعال واقعات", monitoredRegions: "زیر نگرانی علاقے", statusLabel: "حیثیت", live: "لائیو",
    reportIncident: "واقعہ رپورٹ کریں", submitFloodReport: "سیلابی رپورٹ جمع کروائیں",
    submitFloodReportDesc: "اپنے علاقے سے رپورٹ کر کے حکام کی مدد کریں۔ آپ کی رپورٹ ریئل ٹائم میں ٹریک ہوگی۔",
    loginRequired: "لاگ ان ضروری ہے", loginRequiredDesc: "تصدیق شدہ رپورٹس جمع کروانے کے لیے شہری اکاؤنٹ بنائیں۔",
    loginOrRegister: "لاگ ان یا رجسٹر کریں",
    locationAndType: "مقام اور قسم", incidentType: "واقعے کی قسم",
    details: "تفصیلات", description: "تفصیل",
    assessmentContact: "جائزہ اور رابطہ", severityLevel: "شدت کی سطح", contactInfo: "رابطہ کی معلومات",
    visualEvidence: "بصری ثبوت", submitIncidentReport: "واقعے کی رپورٹ جمع کروائیں",
    liveMap: "لائیو نقشہ", incidentOverview: "واقعات کا جائزہ",
    reviewPanel: "جائزہ پینل",
    mapTag: "لائیو نقشہ", mapTitle: "شیلٹرز، ہسپتال اور فعال ردعمل",
    mapDesc: "سسٹم میں رجسٹرڈ ہر شیلٹر، ہسپتال، ریسکیو آپریشن، کمیونٹی رپورٹ اور بند سڑک، رنگ کے ساتھ اور تلاش کے قابل۔",
    mapDescOfficial: "بطور اہلکار، آپ سڑکوں کو بند کے طور پر نشان زد کر سکتے ہیں۔",
    mapDescCitizen: "نقشے کے نشانات ترمیم کرنے کے لیے بطور اہلکار سائن ان کریں۔",
    profileManagement: "پروفائل مینجمنٹ", viewEditAccount: "اپنے اکاؤنٹ کی معلومات دیکھیں اور ترمیم کریں",
    fullName2: "پورا نام", emailAddress2: "ای میل ایڈریس", role: "کردار", memberSince: "رکنیت کب سے",
    editProfile: "پروفائل ترمیم کریں", saveChanges: "تبدیلیاں محفوظ کریں", saving: "محفوظ ہو رہا ہے…", cancel: "منسوخ کریں",
    roleCannotChange: "کردار تبدیل نہیں کیا جا سکتا۔ ضرورت ہو تو منتظم سے رابطہ کریں۔",
    accountInfo: "اکاؤنٹ کی معلومات", accountStatus: "اکاؤنٹ کی حیثیت", active: "فعال", dashboardAccess: "ڈیش بورڈ رسائی",
    citizenDashboardLabel: "شہری ڈیش بورڈ", rescueDashboardLabel: "ریسکیو ڈیش بورڈ",
    govDashboardLabel: "حکومتی ڈیش بورڈ", adminDashboardLabel: "ایڈمن ڈیش بورڈ",
    resetPassword: "پاس ورڈ ری سیٹ کریں", enterEmailForCode: "تصدیقی کوڈ حاصل کرنے کے لیے اپنا ای میل درج کریں",
    enterCodeAndPassword: "کوڈ درج کریں اور نیا پاس ورڈ منتخب کریں",
    sendCode: "تصدیقی کوڈ بھیجیں", sending: "بھیجا جا رہا ہے…",
    verificationCode: "تصدیقی کوڈ", newPassword: "نیا پاس ورڈ", confirmNewPassword: "نئے پاس ورڈ کی تصدیق کریں",
    resettingPassword: "ری سیٹ ہو رہا ہے…", useAnotherEmail: "← دوسرا ای میل استعمال کریں", backToLogin: "← لاگ ان پر واپس جائیں",
    smtpNote: "اس ڈیپلائمنٹ کے لیے کوئی SMTP سروس کنفیگر نہیں ہے — کوڈ اصل ان باکس کی بجائے بیک اینڈ ٹرمینل پر پرنٹ ہوتا ہے۔ ری سیٹ مکمل طور پر فعال ہے۔",
    administration: "انتظامیہ", controlPanel: "کنٹرول پینل",
    controlPanelDesc: "صارفین، الرٹس، شیلٹرز، ہسپتال منظم کریں اور سیلابی پیشگوئیوں کا جائزہ لیں۔",
    totalUsers: "کل صارفین", citizens: "شہری", rescueWorkers: "ریسکیو ورکرز", govOfficials: "سرکاری اہلکار", admins: "منتظمین",
    userManagement: "صارف مینجمنٹ", userManagementDesc: "سسٹم کے صارفین، کردار اور اکاؤنٹ کی حیثیت منظم کریں۔",
    newUser: "+ نیا صارف", newAlert: "+ نیا الرٹ",
    name: "نام", email: "ای میل", status: "حیثیت", actions: "اعمال",
    alertsLog: "الرٹس لاگ", floodPredictions: "سیلابی خطرے کی پیشگوئیاں", export: "ایکسپورٹ",
    allRiskLevels: "تمام خطرے کی سطحیں", shelters: "شیلٹرز", hospitals: "ہسپتال",
    addShelter: "+ شیلٹر شامل کریں", addHospital: "+ ہسپتال شامل کریں", systemEventLog: "سسٹم ایونٹ لاگ",
    viewLog: "لاگ دیکھیں", hideLog: "لاگ چھپائیں", maintainability: "قابل دیکھ بھال",
    retrainModel: "سیلابی خطرے کے ماڈل کو دوبارہ تربیت دیں", mlBackend: "ایم ایل بیک اینڈ",
    rescueCoordination: "ریسکیو کوآرڈینیشن", operationsCenter: "آپریشنز سینٹر",
    operationsCenterDesc: "فعال الرٹس کی نگرانی کریں اور ہنگامی ردعمل ٹیموں کو مربوط کریں۔",
    rescueOperations: "ریسکیو آپریشنز", newOperation: "+ نیا آپریشن",
    location2: "مقام", riskLevel2: "خطرے کی سطح", assignWorker: "ریسکیو ورکر تفویض کریں",
    createNotify: "بنائیں اور ٹیم کو مطلع کریں", unassigned: "غیر تفویض شدہ", markComplete: "مکمل نشان زد کریں", start: "شروع کریں",
    teamLabel: "ٹیم", updatedLabel: "تازہ کاری",
    activeOpsBlockedRoads: "فعال آپریشنز اور بند سڑکیں",
    govOversight: "حکومتی نگرانی", analyticsDashboard: "تجزیاتی ڈیش بورڈ",
    analyticsDashboardDesc: "زیر نگرانی علاقوں میں سیلابی خطرے کا جامع تجزیہ۔",
    filters: "فلٹرز", riskDistribution: "خطرے کی تقسیم", confidenceTrend: "اعتماد کا رجحان",
    topRiskLocations: "زیادہ خطرے والے مقامات", riskOverview: "خطرے کا جائزہ", predictionHistory: "پیشگوئی کی تاریخ",
    footerTaglineFull: "پاکستان کے لیے مصنوعی ذہانت پر مبنی سیلابی خطرے کی پیش گوئی اور آفات کوآرڈینیشن پلیٹ فارم — مشین لرننگ، قابل وضاحت پیشگوئیوں اور شہریوں، ریسکیو ٹیموں اور حکام کے درمیان ریئل ٹائم کوآرڈینیشن کا امتزاج۔",
    communityReportsLink: "کمیونٹی رپورٹس", liveMapLink: "لائیو نقشہ", systemLive: "سسٹم لائیو ہے",
    reportTimelineTitle: "رپورٹ ٹائم لائن", noReportsYet: "ابھی تک کوئی رپورٹ نہیں۔",
    yourReports: "آپ کی رپورٹس", allReports: "تمام کمیونٹی رپورٹس",
    trackStatusDesc: "اپنی جمع کرائی گئی رپورٹس کی حیثیت ٹریک کریں۔",
    filterBySeverity: "شدت", filterByStatus: "حیثیت", filterByRegion: "علاقہ", all: "تمام",
    submitted: "جمع شدہ", underReview: "زیر جائزہ", actionTaken: "کارروائی کی گئی", resolved: "حل شدہ",
    lowSeverity: "کم", mediumSeverity: "درمیانہ", highSeverity: "زیادہ",
    markUnderReview: "زیر جائزہ نشان زد کریں", markActionTaken: "کارروائی شدہ نشان زد کریں", markResolved: "حل شدہ نشان زد کریں",
    peopleConfirmed: "لوگوں نے اس کی تصدیق کی ہے", personConfirmed: "شخص نے اس کی تصدیق کی ہے",
    iSeeThisToo: "میں بھی یہ دیکھ رہا ہوں", confirmed: "تصدیق شدہ",
    searchPlaceholder: "شیلٹرز، ہسپتال، مقامات تلاش کریں…",
    filterShelters: "شیلٹرز", filterHospitals: "ہسپتال", filterRescueOps: "ریسکیو آپریشنز",
    filterCommunityReports: "کمیونٹی رپورٹس", filterBlockedRoads: "بند سڑکیں",
    markBlockedRoad: "+ بند سڑک نشان زد کریں", clickMapToPlace: "جگہ منتخب کرنے کے لیے نقشے پر کلک کریں…",
    routeToNearest: "قریب ترین شیلٹر کا راستہ", findingRoute: "راستہ تلاش ہو رہا ہے…",
    loadingMapData: "نقشے کا ڈیٹا لوڈ ہو رہا ہے…", noOperationsFound: "ابھی تک کوئی ریسکیو آپریشن نہیں۔",
    shelterName: "شیلٹر کا نام", address: "پتہ", capacity: "گنجائش", contact: "رابطہ نمبر",
    saveShelter: "شیلٹر محفوظ کریں", hospitalName: "ہسپتال کا نام", availableServices: "دستیاب خدمات",
    saveHospital: "ہسپتال محفوظ کریں", delete: "حذف کریں", noSheltersRegistered: "ابھی تک کوئی شیلٹر رجسٹرڈ نہیں۔",
    noHospitalsRegistered: "ابھی تک کوئی ہسپتال رجسٹرڈ نہیں۔", searchByNameAddress: "نام یا پتے سے تلاش کریں…",
    realTimeTracking: "ریئل ٹائم ٹریکنگ", trackingIdLabel: "ٹریکنگ آئی ڈی",
    submitReportToTrack: "ٹریکنگ ٹائم لائن دیکھنے کے لیے رپورٹ جمع کروائیں یا نقشے سے کوئی منتخب کریں۔",
    stepSubmittedDesc: "جمع کروا دی گئی اور جائزے کے لیے قطار میں", stepReviewDesc: "جائزہ ٹیم اثر کا جائزہ لے رہی ہے",
    stepActionDesc: "حکام ردعمل پر عمل درآمد کر رہے ہیں", stepResolvedDesc: "مسئلہ حل اور دستاویزی کر دیا گیا",
    officialReviewWorkspace: "سرکاری جائزہ ورک اسپیس",
    filterReportsDesc: "واقعاتی رپورٹس کو حیثیت، علاقے یا شدت کے لحاظ سے فلٹر کریں اور کارروائی کریں۔",
    allSeverity: "تمام شدت", allStatus: "تمام حیثیت", allRegions: "تمام علاقے",
    colTrackingId: "ٹریکنگ آئی ڈی", colLocation: "مقام", colSeverity: "شدت", colStatus: "حیثیت",
    colSubmittedBy: "جمع کروانے والا", colAction: "عمل",
    reviewAction: "جائزہ", actionAction: "کارروائی", resolveAction: "حل کریں",
    view: "دیکھیں", deactivate: "غیر فعال کریں", activate: "فعال کریں", inactive: "غیر فعال",
    assessmentResult: "تجزیے کا نتیجہ", humidityPct: "نمی (%)", matchedTo: "مماثل شہر",
    modelInputsUsed: "ماڈل میں استعمال شدہ ان پٹس", noRegisteredHospitals: "کوئی رجسٹرڈ ہسپتال نہیں ملا۔",
    noRegisteredShelters: "کوئی رجسٹرڈ شیلٹر نہیں ملا۔", surfaceSoilMoisture: "سطحی مٹی کی نمی",
    whyThisPrediction: "یہ پیشگوئی کیوں؟", windSpeedMs: "ہوا کی رفتار (m/s)",
    fetchingWeather: "اس شہر کا لائیو موسم حاصل ہو رہا ہے…",
    weatherFetchFailed: "اس مقام کا موسم حاصل نہیں ہو سکا (ہجے چیک کریں) — بارش اور درجہ حرارت خود درج کریں۔",
    riverLevelHint: "حوالے کے لیے ریکارڈ کیا گیا — جو آپ دیکھ سکتے ہیں وہ منتخب کریں، درست پیمائش ضروری نہیں۔",
    showAdvanced: "+ ایڈوانسڈ موسمی ان پٹس دکھائیں (نمی، ہوا، مٹی کی نمی)",
    hideAdvanced: "− ایڈوانسڈ موسمی ان پٹس چھپائیں (نمی، ہوا، مٹی کی نمی)",
    modelAttributesNote: "ماڈل 20 تربیت یافتہ اوصاف استعمال کرتا ہے۔ اپنا شہر منتخب کرنے کے بعد نمی، ہوا اور مٹی کی نمی خودکار طور پر لائیو موسمی ڈیٹا سے حاصل ہو جاتی ہیں — آپ کو کچھ اور بھرنے کی ضرورت نہیں۔",
    shapBreakdownNote: "SHAP تجزیہ — مثبت بارز نے خطرہ بڑھایا، منفی بارز نے کم کیا۔",
    modelInputsNote: "وہ تمام اوصاف جو ماڈل کو اصل میں تربیت دی گئی اور اس پیشگوئی کے لیے فیڈ کی گئیں (شہر کے علاوہ، اوپر دکھایا گیا)۔",
    basedOnTypedCity: "آپ کے درج کردہ شہر کی بنیاد پر", basedOnDeviceLocation: "آپ کے آلے کے موجودہ مقام کی بنیاد پر",
    kmAway: "کلومیٹر دور", capacityLabel: "گنجائش", viewOnMap: "نقشے پر دیکھیں →",
    couldntGetLocation: "آپ کا مقام حاصل نہیں ہو سکا۔ براؤزر کی لوکیشن اجازت چیک کریں اور دوبارہ کوشش کریں۔",
    findingNearby: "قریبی شیلٹرز اور ہسپتال تلاش ہو رہے ہیں…", leaveBlankAvg: "شہر کی اوسط کے لیے خالی چھوڑیں",
    selectYourCity: "اپنا شہر منتخب کریں", cityCoverageNote: "پاکستان کے 53 بڑے شہر شامل ہیں۔",
    selectRainfallLevel: "منتخب کریں کہ باہر کیا نظر آ رہا ہے",
    rainfallNone: "بارش نہیں", rainfallLight: "ہلکی بوندا باندی", rainfallModerate: "درمیانی بارش",
    rainfallHeavy: "تیز بارش", rainfallVeryHeavy: "بہت تیز / مسلسل بارش",
    actualDetected: "اصل پتہ چلا", rainfallHint: "بس وہ منتخب کریں جو باہر نظر آ رہا ہے — درست پیمائش ضروری نہیں۔",
    leaveBlankAvg2: "یقین نہیں — شہر کی اوسط استعمال کریں", humidityDry: "خشک / آرام دہ", humidityNormal: "معمول",
    humidityHumid: "نم / چپچپا", humidityVeryHumid: "بہت زیادہ نم",
    windCalm: "پرسکون — بہت کم یا کوئی ہوا نہیں", windBreezy: "ہلکی ہوا", windStrong: "تیز ہوا",
    soilMoistureRemovedNote: "مٹی کی نمی ایسی چیز نہیں جسے آنکھ سے پرکھا جا سکے، اس لیے ہم ہمیشہ اسے آپ کے شہر اور موسم کے تاریخی ڈیٹا سے اندازہ کرتے ہیں۔",
    locationRequired: "براہ کرم اپنا شہر منتخب کریں", rainfallRequired: "براہ کرم بارش کی سطح منتخب کریں",
    rainfallPositive: "بارش ایک مثبت نمبر ہونا چاہیے", rainfallUnrealistic: "بارش کی مقدار غیر حقیقی لگتی ہے (بہت زیادہ)",
    temperatureRequired: "درجہ حرارت ضروری ہے", temperatureMustBeNumber: "درجہ حرارت ایک نمبر ہونا چاہیے",
    temperatureRange: "درجہ حرارت -10°C سے 60°C کے درمیان ہونا چاہیے", invalidEmailFormat: "براہ کرم درست ای میل ایڈریس درج کریں",
    fillRequiredFields: "جمع کروانے سے پہلے تمام ضروری فیلڈز مکمل کریں۔",
    locationTooShort: "براہ کرم زیادہ مخصوص مقام درج کریں (کم از کم 3 حروف)۔",
    descriptionTooShort: "براہ کرم واقعے کی مزید تفصیل بتائیں (کم از کم 10 حروف)۔",
    invalidPhoneFormat: "براہ کرم درست پاکستانی فون نمبر درج کریں (مثلاً 03001234567)۔",
    incidentReportSubmitted: "واقعے کی رپورٹ کامیابی سے جمع ہو گئی", couldNotSubmitReport: "رپورٹ جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
    capacityMustBePositive: "گنجائش ایک مثبت نمبر ہونا چاہیے", passwordTooShort: "پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے",
    predictionFailedGeneric: "پیشگوئی حاصل نہیں ہو سکی۔ براہ کرم چیک کریں بیک اینڈ سرور چل رہا ہے اور دوبارہ کوشش کریں۔",
    floodRiskAnalysisCompleted: "سیلابی خطرے کا تجزیہ مکمل ہوا!",
    liveConditionsDetected: "آپ کے شہر کے لیے لائیو حالات معلوم ہوئے",
    soil7dayAvgLabel: "7 دن کی مٹی کی اوسط",
    policyPlanning: "پالیسی منصوبہ بندی", resourceGapAnalysis: "وسائل کی کمی کا تجزیہ",
    resourceGapDesc: "وہ شہر جو درمیانہ/زیادہ خطرے میں ہیں اور جن کے پاس مجموعی طور پر 3 یا کم شیلٹرز/ہسپتال ہیں (نیٹ ورک اوسط سے کم)، کم وسائل کے طور پر نشان زد ہیں۔",
    underResourced: "کم وسائل",
    comparativeAnalysis: "تقابلی تجزیہ", multiCityComparison: "متعدد شہروں کا موازنہ",
    selectCityToCompare: "موازنے کے لیے شہر منتخب کریں", latestRisk: "حالیہ خطرہ", highRiskCount: "زیادہ خطرے کی پیشگوئیاں",
    reporting: "رپورٹنگ", districtReport: "ضلعی رپورٹ",
    districtReportDesc: "شہر کی حالیہ سیلابی خطرے کی تاریخ اور وسائل کی کوریج کا سرکاری پی ڈی ایف خلاصہ ڈاؤن لوڈ کریں۔",
    downloadReport: "رپورٹ ڈاؤن لوڈ کریں",
    officialCommunication: "سرکاری مواصلات", publicAdvisories: "عوامی ایڈوائزریز",
    advisoriesDesc: "پالیسی سطح کی عوامی رہنمائی، ہنگامی الرٹس سے الگ — مثلاً موسمی تیاری کے نوٹسز۔",
    issueAdvisory: "+ ایڈوائزری جاری کریں", advisoryTitlePh: "ایڈوائزری کا عنوان", advisoryMessagePh: "ایڈوائزری کا پیغام",
    advisoryRegionPh: "علاقہ (مثلاً سندھ، یا 'تمام علاقے' چھوڑ دیں)", noAdvisoriesYet: "ابھی تک کوئی ایڈوائزری جاری نہیں ہوئی۔",
    withdraw: "واپس لیں", confirmWithdrawAdvisory: "یہ ایڈوائزری واپس لیں؟ یہ اب عوام کو نہیں دکھائی جائے گی۔",
    reportGenerationFailed: "رپورٹ تیار نہیں ہو سکی۔ چیک کریں بیک اینڈ میں fpdf2 انسٹال ہے۔",
    emergencyResponse: "ہنگامی ردعمل", highRiskAlerts: "زیادہ خطرے کے الرٹس",
    highRiskAlertsDesc: "فعال درمیانہ/زیادہ خطرے کے الرٹس — ریسکیو ورکر تفویض کر کے ردعمل آپریشن بھیجیں۔",
    noActiveAlerts: "ابھی کوئی فعال درمیانہ/زیادہ خطرے کا الرٹ نہیں۔",
    assignRescueWorker: "ریسکیو ورکر تفویض کریں", selectRescueWorker: "ریسکیو ورکر منتخب کریں",
    operationNotesPh: "آپریشن کے نوٹس (اختیاری)", confirmAssignment: "تفویض کی تصدیق کریں",
    operationAssignedMsg: "ریسکیو ورکر تفویض ہو گیا — آپریشن بن گیا۔",
    workforceOversight: "افرادی قوت کی نگرانی", rescueWorkerDirectory: "ریسکیو ورکر ڈائریکٹری",
    rescueWorkerDirectoryDesc: "تمام رجسٹرڈ ریسکیو ورکرز — یہاں ان کی فعال حیثیت منظم کریں۔",
    noRescueWorkersYet: "ابھی تک کوئی ریسکیو ورکر رجسٹرڈ نہیں۔", assignedTo: "تفویض شدہ برائے",
    operationsMonitoring: "آپریشنز کی نگرانی", rescueOperationsOverview: "ریسکیو آپریشنز کا جائزہ",
    rescueOperationsOverviewDesc: "ہر ضلع میں فی الحال جاری یا مکمل ہونے والے تمام ریسکیو آپریشنز کی لائیو حیثیت۔",
    donationPledgesOverviewDesc: "عطیہ دہندگان اور اداروں کی طرف سے پیش کردہ وسائل کے وعدے، کوآرڈینیشن اور منصوبہ بندی کے لیے۔",
    historicalContext: "تاریخی پس منظر", seasonalTrend: "موسمی / تاریخی رجحان",
    seasonalTrendDesc: "اصل پیشگوئی کی تاریخ مہینے کے حساب سے گروپ کی گئی — حالیہ مہینوں میں سیلابی خطرہ کیسے تبدیل ہوا۔",
    escalationLog: "ہنگامی ایسکلیشن لاگ",
    escalationLogDesc: "الرٹس سے کیے گئے ریسکیو ورکر تفویضات کا ریکارڈ، جوابدہی کے لیے — ایڈوائزریز نیچے الگ سے ٹریک ہوتی ہیں۔",
    tabAnalytics: "تجزیات", tabEmergencyResponse: "ہنگامی ردعمل", tabPolicyPlanning: "پالیسی اور منصوبہ بندی", tabCommunication: "مواصلات",
    tabMyOperations: "میرے آپریشنز", tabTeamOverview: "ٹیم کا جائزہ", tabMapNavigation: "نقشہ اور رہنمائی",
    onDuty: "ڈیوٹی پر", offDuty: "ڈیوٹی سے باہر", myPerformance: "میری کارکردگی", myStatsTitle: "میرے اعداد و شمار",
    activeLabel: "فعال", myAssignedOperations: "مجھے تفویض کردہ آپریشنز",
    myAssignedOperationsDesc: "وہ آپریشنز جو خاص طور پر آپ کو تفویض کیے گئے ہیں۔",
    noOperationsAssignedToMe: "ابھی آپ کو کوئی آپریشن تفویض نہیں ہوا۔",
    backupNeeded: "بیک اپ درخواست کی گئی", getRoute: "راستہ حاصل کریں", requestBackup: "بیک اپ کی درخواست کریں",
    addUpdateNotePh: "ایک فوری اپڈیٹ شامل کریں (مثلاً 'راستے میں ہوں'، 'پہنچ گیا')…", post: "پوسٹ کریں",
    backupRequestedMsg: "بیک اپ کی درخواست ہو گئی — کوآرڈینیٹرز کے لیے نشان زد۔",
    locationNotResolvable: "اس مقام کے احداثیات معلوم نہیں ہو سکے راستے کے لیے۔",
    tabTeamResources: "ٹیم اور وسائل", coordination: "کوآرڈینیشن",
    onDutyWorkersTitle: "ابھی کون ڈیوٹی پر ہے", onDutyWorkersDesc: "وہ ریسکیو ورکرز جو فی الحال دستیاب ہیں۔",
    noOneOnDuty: "فی الحال کوئی بھی ڈیوٹی پر نشان زد نہیں۔",
    teamRosterTitle: "ٹیم کی فہرست",
    equipmentTrackerTitle: "سامان اور وسائل", equipmentTrackerDesc: "سامان کو کسی جاری آپریشن کے ساتھ منسلک کریں، یا اسٹیٹس بٹن دبا کر دستیاب/زیر استعمال نشان زد کریں۔",
    statusAvailable: "دستیاب", statusInUse: "زیر استعمال",
    addEquipmentBtn: "سامان شامل کریں", equipmentNamePh: "مثلاً لائف جیکٹس", quantityLabel: "تعداد",
    unassignedEquipment: "کسی آپریشن کے ساتھ منسلک نہیں", assignedToLabel: "بھیجا گیا",
    availableOfTotal: "دستیاب", freeUpBtn: "یہ یونٹ آزاد کریں", selectOperationPh: "آپریشن منتخب کریں…",
    qtyShort: "تعداد", deployBtn: "بھیجیں", noActiveOpsHint: "ابھی بھیجنے کے لیے کوئی جاری آپریشن نہیں۔",
    continuity: "تسلسل", shiftHandoverTitle: "شفٹ کی منتقلی کے نوٹس",
    shiftHandoverDesc: "اگلی شفٹ کے لیے نوٹ چھوڑیں — جاری حالات، دھیان رکھنے کی باتیں۔",
    handoverNotePh: "مثلاً 'سیکٹر 4 میں ابھی بھی پانی ہے، نظر رکھیں'…", noHandoverNotesYet: "ابھی تک کوئی ہینڈ اوور نوٹ نہیں۔",
    priorityNormal: "عام", priorityWatch: "نظر رکھیں", priorityUrgent: "اہم",
    markNoteResolved: "حل شدہ نشان زد کریں", reopenNote: "دوبارہ کھولیں",
    rescueTeamsTitle: "ریسکیو ٹیمیں", rescueTeamsDesc: "ورکرز کو مکمل ٹیم (3-4 افراد) میں گروپ کریں تاکہ سیلاب زدہ علاقے کو صرف ایک نام نہیں بلکہ اصل رسپانس کریو ملے۔",
    newTeamBtn: "نئی ٹیم", teamNameLabel: "ٹیم کا نام", teamNamePh: "مثلاً ٹیم الفا",
    teamMembersLabel: "ٹیم کے ارکان", teamNeedsTwoHint: "ٹیم بنانے کے لیے کم از کم 2 ارکان منتخب کریں۔",
    createTeamBtn: "ٹیم بنائیں", noTeamsYet: "ابھی تک کوئی ریسکیو ٹیم نہیں — کسی آپریشن کو مکمل کریو دینے کے لیے ایک بنائیں۔",
    noTeamsYetHint: "ابھی کوئی ٹیم نہیں — نیچے ٹیم کی فہرست میں ایک بنائیں، یا فی الحال ایک فرد کو تفویض کریں۔",
    deleteTeam: "ہٹا دیں", membersLabel: "ارکان",
    assignModeTeam: "ٹیم تفویض کریں", assignModeIndividual: "ایک فرد تفویض کریں",
    communityReportsHeading: "کمیونٹی رپورٹس", reportedByLabel: "رپورٹ کرنے والا",
    linkedOperationLabel: "منسلک آپریشن", dispatchTeamBtn: "ٹیم بھیجیں",
    reportDispatchedMsg: "رپورٹ بھیج دی گئی — ریسکیو آپریشن بن چکا ہے۔",
    volunteersTitle: "رضاکار", volunteersDesc: "وہ لوگ جنہوں نے کمیونٹی پیج کے \"Get Involved\" فارم سے رجسٹر کیا — جب اضافی مدد چاہیے ہو تو کسی کو قریبی آپریشن سے منسلک کریں۔",
    noVolunteersYet: "ابھی تک کوئی رضاکار رجسٹر نہیں ہوا۔", assignToOperationDropdown: "کسی آپریشن سے منسلک کریں…",
    recordKeeping: "ریکارڈ رکھنا", historicalSearchTitle: "ماضی کے آپریشنز",
    historicalSearchDesc: "مقام، ٹیم، یا نوٹس سے ماضی کے مکمل شدہ آپریشنز تلاش کریں۔",
    historicalSearchPh: "مقام، ٹیم، یا نوٹس سے تلاش کریں…", noHistoricalResults: "آپ کی تلاش سے کوئی مکمل شدہ آپریشن میل نہیں کھاتا۔",
    showingXofYPredictions: "{y} میں سے {x} پیشگوئیاں دکھائی جا رہی ہیں", showingFirst20: "پہلے 20 نتائج دکھائے جا رہے ہیں۔ مزید ڈیٹا کے لیے فلٹرز استعمال کریں۔",
    liveConditionsNote: "لائیو موسمی ڈیٹا سے خودکار حاصل کیا گیا — یہاں کچھ بھرنے کی ضرورت نہیں۔",
    egLahore: "مثلاً لاہور", enterCityToAutofill: "خودکار پُر کرنے کے لیے اوپر اپنا شہر درج کریں، یا خود ٹائپ کریں",
    alertMessage: "الرٹ پیغام", alertStatistics: "الرٹ اعداد و شمار", cancelled: "منسوخ شدہ",
    close: "بند کریں", createAlertBtn: "الرٹ بنائیں", createNewUserBtn: "نیا صارف بنائیں",
    highRiskAlerts: "زیادہ خطرے کے الرٹس", loadingAdminData: "ایڈمن ڈیٹا لوڈ ہو رہا ہے...",
    noEventsLogged: "ابھی تک کوئی ایونٹ لاگ نہیں ہوا۔", noPredictionsMatch: "کوئی پیشگوئی ان فلٹرز سے مماثل نہیں۔",
    passwordLabel: "پاس ورڈ", rainfallLabel: "بارش", registeredAccounts: "رجسٹرڈ اکاؤنٹس",
    reviewUserNote: "اس صارف کا جائزہ لیں اور کنٹرول پینل سے حیثیت اپڈیٹ کریں۔",
    riskLevelLabel: "خطرے کی سطح", riskAssessmentsMade: "کیے گئے خطرے کے جائزے", riskLabel: "خطرہ",
    riverLevelLabel: "دریا کی سطح", roleLabel: "کردار", sheltersHospitalsBlockedRoads: "شیلٹرز، ہسپتال اور بند سڑکیں",
    systemReports: "سسٹم رپورٹس", systemAlertsGenerated: "بنائے گئے سسٹم الرٹس", timestamp: "ٹائم اسٹیمپ",
    totalAlerts: "کل الرٹس", totalPredictionsLabel: "کل پیشگوئیاں", totalUsersLabel: "کل صارفین",
    userDistribution: "صارفین کی تقسیم", userDetails: "صارف کی تفصیلات",
    enterAlertMessage: "الرٹ پیغام درج کریں", enterEmail: "ای میل درج کریں", enterLocation: "مقام درج کریں",
    enterName: "نام درج کریں", enterPassword: "پاس ورڈ درج کریں", searchByNameEmailRole: "نام، ای میل یا کردار سے تلاش کریں…",
    alertDetails: "الرٹ کی تفصیلات", emergencyStatus: "ہنگامی حیثیت", highRiskAreas: "زیادہ خطرے والے علاقے",
    noHighRiskAreas: "کوئی زیادہ خطرے والا علاقہ نہیں ملا", noMediumRiskAreas: "کوئی درمیانہ خطرے والا علاقہ نہیں ملا",
    whatNeedsToHappen: "یہاں کیا ہونا چاہیے؟", egSukkur: "مثلاً سکھر",
    allLocations: "تمام مقامات", allTime: "تمام وقت", dateRange: "تاریخ کی حد", dateLabel: "تاریخ",
    lastMonth: "پچھلا مہینہ", lastWeek: "پچھلا ہفتہ", loadingAnalytics: "تجزیاتی ڈیٹا لوڈ ہو رہا ہے...", todayLabel: "آج",
    dragDropImage: "تصویر یہاں ڈریگ اینڈ ڈراپ کریں", loginToSubmit: "جمع کروانے کے لیے لاگ ان کریں", removeLabel: "ہٹائیں",
    cityRegionNeighbourhood: "شہر، علاقہ یا محلہ",
    confirmPasswordLabel: "پاس ورڈ کی تصدیق کریں", joinPlatform: "باخبر رہنے کے لیے پلیٹ فارم میں شامل ہوں",
    whoAreYou: "آپ کون ہیں؟", confirmYourPassword: "اپنے پاس ورڈ کی تصدیق کریں", createPasswordPh: "پاس ورڈ بنائیں",
    enterYourEmail: "اپنا ای میل درج کریں", enterYourFullName: "اپنا پورا نام درج کریں",
    rememberMe: "مجھے یاد رکھیں", enterYourPassword: "اپنا پاس ورڈ درج کریں",
    citizenSingular: "شہری", rescueWorkerSingular: "ریسکیو ورکر",
    normalNoThreats: "معمول - کوئی فوری خطرہ نہیں", orClickToBrowse: "یا براؤز کرنے کے لیے کلک کریں",
    incidentFlooding: "سیلاب", incidentLandslide: "لینڈ سلائیڈ", incidentRoadBlockage: "سڑک کی بندش",
    incidentWaterContamination: "پانی کی آلودگی", incidentInfraDamage: "بنیادی ڈھانچے کو نقصان",
    incidentEvacuation: "انخلا ضروری",
    recentAlertsTitle: "حالیہ الرٹس", noAlertsYet: "ابھی تک کوئی الرٹ نہیں۔", noRecordedHistory: "ابھی تک کوئی تاریخ ریکارڈ نہیں",
    forecastTitle: "3 دن کا خطرہ آؤٹ لک", getForecast: "پیشگوئی حاصل کریں", forecastError: "پیشگوئی حاصل نہیں ہو سکی — تھوڑی دیر میں دوبارہ کوشش کریں۔",
    forecastHint: "دیکھیں کہ اگلے 3 دنوں میں خطرہ کیسے تبدیل ہو سکتا ہے", yourCity: "آپ کے شہر", loadingEllipsis: "لوڈ ہو رہا ہے…",
    modelComparisonTitle: "ماڈل موازنہ", modelsAgree: "دونوں ماڈل اس پیشگوئی پر متفق ہیں۔",
    modelsDisagree: "یہ ماڈل متفق نہیں ہیں — اضافی احتیاط کریں اور اوپر SHAP تجزیہ دیکھیں۔",
    safetyNetwork: "حفاظتی نیٹ ورک", familyContactsTitle: "خاندانی اور ہنگامی رابطے", addContact: "+ رابطہ شامل کریں",
    familyContactsDesc: "ایسے لوگ شامل کریں جنہیں آپ باخبر رکھنا چاہتے ہیں۔ جب آپ کے علاقے کے لیے زیادہ خطرے کا الرٹ جاری ہو، تو آپ ایک ٹیپ میں سب کو مطلع کر سکتے ہیں (اس ڈیپلائمنٹ کے لیے کوئی SMS سروس کنفیگر نہیں ہے، اس لیے اطلاعات لاگ کی جاتی ہیں، اصل میں نہیں بھیجی جاتیں)۔",
    namePh: "نام", phonePh: "فون", relationPh: "رشتہ (مثلاً بہن)", saveContact: "رابطہ محفوظ کریں",
    noContactsYet: "ابھی تک کوئی رابطہ شامل نہیں کیا۔", removeContact: "ہٹائیں", notifyAllContacts: "ابھی سب رابطوں کو مطلع کریں",
    downloadPdfBtn: "پی ڈی ایف ڈاؤن لوڈ کریں",
    modelAccuracyOverTime: "وقت کے ساتھ ماڈل کی درستگی",
    noRetrainEvents: "ابھی تک کوئی دوبارہ تربیت نہیں ہوئی — جب بھی ماڈل دوبارہ تربیت یافتہ ہوگا، درستگی یہاں ریکارڈ ہوگی۔",
    predictionConfidenceTrend: "پیشگوئی کے اعتماد کا رجحان", notEnoughHistory: "رجحان دکھانے کے لیے ابھی کافی پیشگوئی کی تاریخ موجود نہیں۔",
    registeredVolunteers: "رجسٹرڈ رضاکار", noVolunteersYet: "ابھی تک کوئی رضاکار رجسٹرڈ نہیں۔ شہری کمیونٹی پیج سے رجسٹر کر سکتے ہیں۔",
    phoneCol: "فون", cityCol: "شہر", skillsCol: "مہارتیں", resourceCoordination: "وسائل کوآرڈینیشن",
    donationPledges: "عطیات کے وعدے", noDonationsYet: "ابھی تک کوئی عطیہ نہیں دیا گیا۔",
    checkInQr: "چیک ان QR", hideQr: "QR چھپائیں", qrInstructions: "اسے شیلٹر کے داخلی راستے پر پرنٹ یا دکھائیں۔ آنے والے اسکین کر کے چیک ان کریں۔",
    downloadUsersReport: "صارفین کی رپورٹ ڈاؤن لوڈ کریں", downloadAlertsReport: "الرٹس کی رپورٹ ڈاؤن لوڈ کریں", downloadPredictionsReport: "پیشگوئیوں کی رپورٹ ڈاؤن لوڈ کریں",
    getInvolved: "شامل ہوں", registerVolunteerTitle: "بطور رضاکار رجسٹر کریں",
    registerVolunteerDesc: "ریسکیو ٹیمیں ضرورت پڑنے پر آپ سے رابطہ کر سکتی ہیں۔", registerAsVolunteerBtn: "بطور رضاکار رجسٹر کریں",
    supportReliefEfforts: "امدادی کوششوں میں مدد کریں", pledgeDonationTitle: "عطیہ دینے کا وعدہ کریں",
    pledgeDonationDesc: "سامان، فنڈز یا آلات — کوآرڈینیٹرز کو بتائیں کہ آپ کیا دے سکتے ہیں۔", pledgeDonationBtn: "عطیہ کا وعدہ کریں",
    fullNamePh: "پورا نام", phoneNumberPh: "فون نمبر", yourCityPh: "آپ کا شہر",
    skillsExamplePh: "مہارتیں (مثلاً فرسٹ ایڈ، ڈرائیونگ، تیراکی)", nameOrgPh: "آپ کا نام / ادارہ",
    contactNumberPh: "رابطہ نمبر", itemExamplePh: "چیز (مثلاً کمبل)",
    thankYouVolunteer: "رجسٹریشن کا شکریہ — ریسکیو ٹیمیں اب آپ کو دیکھ سکتی ہیں۔",
    thankYouDonation: "شکریہ — آپ کا وعدہ ریکارڈ کر لیا گیا ہے۔",
    whyMatters: "یہ کیوں اہم ہے", recentFloodsTitle: "پاکستان کے حالیہ بڑے سیلاب",
    flood2010Title: "دریائے سندھ کے سیلاب",
    flood2010Desc: "پاکستان کی تاریخ کے شدید ترین سیلابوں میں سے ایک، جس نے ملک کے تقریباً پانچویں حصے کو متاثر کیا اور دریائے سندھ کے بیسن میں لاکھوں افراد بے گھر ہوئے۔",
    flood2011Title: "سندھ کے سیلاب",
    flood2011Desc: "2010 کی تباہی کے ایک سال بعد شدید مون سون بارشوں نے سندھ بھر میں وسیع پیمانے پر سیلاب لایا، دوبارہ بڑی دیہی آبادی بے گھر ہوئی۔",
    flood2022Title: "مون سون کے 'سپر سیلاب'",
    flood2022Desc: "ریکارڈ مون سون بارش اور گلیشیئر پگھلنے سے سندھ، بلوچستان اور جنوبی پنجاب میں تباہ کن سیلاب آیا، جو ملکی تاریخ کی مہنگی ترین آفات میں سے ایک ہے۔",
    floodsFootnote: "یہ اعداد و شمار عمومی تاریخی پس منظر ہیں، لائیو اعداد و شمار نہیں۔ ابتدائی پیشگوئی اور کوآرڈینیشن — جو یہ پلیٹ فارم فراہم کرتا ہے — ایسے واقعات کے اثرات کم کرنے کا مؤثر ترین طریقہ ہے۔",
    shelterCheckin: "شیلٹر چیک ان", youveArrived: "آپ پہنچ گئے",
    checkedInSuccess: "کامیابی سے چیک ان ہو گیا۔ محفوظ رہیں — یہاں سے مدد مربوط کی جا رہی ہے۔",
    tellUsName: "اختیاری طور پر اپنا نام بتائیں تاکہ ریسپانڈرز کو معلوم ہو کون پہنچا ہے۔", yourNamePh: "آپ کا نام (اختیاری)",
    checkingIn: "چیک ان ہو رہا ہے…", checkInBtn: "چیک ان کریں", checkInError: "کچھ غلط ہو گیا — براہ کرم شیلٹر عملے کو بتائیں۔",
    myReports: "میری رپورٹس", myReportsDesc: "ٹریکنگ ٹائم لائن دیکھنے کے لیے کوئی رپورٹ منتخب کریں۔",
    noReportsSubmitted: "آپ نے ابھی تک کوئی رپورٹ جمع نہیں کروائی۔", submittedOn: "جمع شدہ",
    assignTeamPrompt: "اس آپریشن کے لیے ریسکیو ٹیم تفویض کریں (اختیاری، خالی چھوڑ سکتے ہیں):",
    rescueOpCreatedMsg: "کارروائی کی گئی — ریسکیو آپریشن بن گیا", reportSetTo: "رپورٹ کی حیثیت مقرر کی گئی",
    peopleRescuedPrompt: "کتنے لوگ بچائے گئے؟ (نمبر درج کریں)",
    resourcesUsedPrompt: "کون سے وسائل استعمال ہوئے؟ (مثلاً 2 کشتیاں، طبی سامان)",
    completionNotesPrompt: "کوئی تکمیلی نوٹس؟",
    operationMarkedAs: "آپریشن کی حیثیت مقرر کی گئی", couldNotUpdateOp: "آپریشن کی حیثیت اپڈیٹ نہیں ہو سکی۔",
    completedIn: "مکمل ہوا میں", peopleRescuedLabel: "بچائے گئے لوگ", resourcesUsedLabel: "استعمال شدہ وسائل",
    nearestShelter: "قریب ترین شیلٹر", nearestHospital: "قریب ترین ہسپتال", assignVolunteerLabel: "+ رضاکار تفویض کریں",
    rescueStatsLabel: "ریسکیو اعداد و شمار", operationsOverviewLabel: "آپریشنز کا جائزہ",
    totalOperationsLabel: "کل آپریشنز", completedLabel: "مکمل شدہ", avgMinutesLabel: "اوسط تکمیل (منٹ)",
    completionReportTitle: "تکمیلی رپورٹ", completionReportDesc: "اس آپریشن کو مکمل نشان زد کرنے سے پہلے جو ہوا وہ لکھیں — یہ آپریشن کے ساتھ مستقل طور پر محفوظ ہو جائے گا۔",
    resourcesUsedPlaceholder: "مثلاً 2 کشتیاں، طبی سامان", completionNotesLabel: "نوٹس",
    completionNotesPlaceholder: "مثلاً تمام خاندان محفوظ طریقے سے نکال لیے گئے", submitAndComplete: "جمع کریں اور مکمل نشان زد کریں",
    tipEvacuate: "فوری طور پر بلند مقام کی طرف منتقل ہو جائیں", tipFollowAuthorities: "حکام کی ہنگامی ہدایات پر عمل کریں",
    tipEmergencyKit: "ضروری اشیاء کے ساتھ ایمرجنسی کٹ تیار رکھیں", tipOfficialChannels: "سرکاری ذرائع سے باخبر رہیں",
    tipMonitorWeather: "موسم کی اپڈیٹس کو باقاعدگی سے دیکھیں", tipPrepareSupplies: "ہنگامی سامان تیار کریں",
    tipKnowRoutes: "اپنے علاقے کے انخلا کے راستے جانیں", tipStayAlert: "مزید وارننگز کے لیے چوکنا رہیں",
    tipNormalActivities: "آگاہی کے ساتھ معمول کی سرگرمیاں جاری رکھیں", tipBasicSupplies: "بنیادی ہنگامی سامان رکھیں",
    tipWeatherConditions: "موسمی حالات سے باخبر رہیں", tipFamilyComm: "خاندان سے رابطہ برقرار رکھیں",
    tipStayInformed: "باخبر رہیں اور تیار رہیں",
    weatherAutoFilled: "بارش اور درجہ حرارت لائیو موسمی ڈیٹا سے خود بخود پُر ہو گئے", autoFilledEditable: "خود بخود پُر، قابل تبدیل",
    findHelpNear: "قریب مدد تلاش کریں", retrainDescription: "ماڈل کو دوبارہ تربیت دینے کے لیے نیا تاریخی ڈیٹاسیٹ (CSV) اپلوڈ کریں۔ اس میں flood_label کالم اور city کالم یا موجودہ اوصاف کالمز ضروری ہیں۔ دوبارہ تربیت یافتہ ماڈل کو ایک الگ رکھے گئے ڈیٹا پر جانچا جاتا ہے اور خودکار طور پر تب ہی نافذ ہوتا ہے جب یہ FR10-04 کے مطلوبہ کم از کم 80% درستگی تک پہنچے — ورنہ اسے مسترد کر دیا جاتا ہے اور موجودہ ماڈل چلتا رہتا ہے۔",
    serviceEmergency: "ایمرجنسی",
    statusPrefix: "حیثیت", riskPrefix: "خطرہ", severityPrefix: "شدت",
    statusAssigned: "تفویض شدہ", statusInProgress: "جاری ہے", statusCompleted: "مکمل",
    statusBlocked: "بند", statusCleared: "صاف", markAsCleared: "صاف کے طور پر نشان زد کریں",
    floodRiskAnalysisFor: "سیلابی خطرے کا تجزیہ برائے", matchedCityLabel: "مماثل شہر",
    inputParameters: "ان پٹ پیرامیٹرز", riverLevelNote: "ریکارڈ کیا گیا، ماڈل میں استعمال نہیں ہوا — تربیتی ڈیٹا میں دریا کی سطح شامل نہیں تھی",
    mlModelPrediction: "ایم ایل ماڈل پیشگوئی", floodRiskWord: "سیلابی خطرہ", modelConfidenceLabel: "ماڈل اعتماد",
    riskAssessmentLabel: "خطرے کا جائزہ", generatedUsingModel: "تیار کردہ بذریعہ", modelTrainedOnData: "ماڈل، 10 شہروں کے 24 سالہ تاریخی سیلابی ڈیٹا پر تربیت یافتہ۔",
    riskSummaryHigh: "نازک سیلابی خطرہ محسوس ہوا۔ فوری انخلا اور ہنگامی اقدامات ضروری ہیں۔",
    riskSummaryMedium: "درمیانہ سیلابی خطرہ۔ چوکنا رہیں اور حالات پر گہری نظر رکھیں۔",
    riskSummaryLow: "کم سیلابی خطرہ۔ حالات محفوظ نظر آتے ہیں لیکن چوکنا رہیں۔",
    featTemperature: "درجہ حرارت", featHumidity: "نمی", featWindSpeed: "ہوا کی رفتار",
    featSoilMoistureTop: "سطحی مٹی کی نمی", featSoil7dayAvg: "7 دن کی مٹی کی نمی کی اوسط",
    featMonth: "مہینہ", featYear: "سال", featIsMonsoon: "مون سون موسم", featSeason: "موسم",
    featRainIntensity: "بارش کی شدت", featCityPrefix: "شہر",
    enterRegisteredEmail: "اپنا رجسٹرڈ ای میل درج کریں", checkBackendTerminal: "بیک اینڈ ٹرمینل چیک کریں",
    createNewPasswordPh: "نیا پاس ورڈ بنائیں", repeatNewPassword: "نیا پاس ورڈ دہرائیں",
    enterFullNamePh: "اپنا پورا نام درج کریں", enterEmailAddressPh: "اپنا ای میل ایڈریس درج کریں",
    loadingDots: "لوڈ ہو رہا ہے...", brandName: "فلڈ ڈیزاسٹر مینجمنٹ سسٹم",
    exportCsv: "رپورٹ ایکسپورٹ کریں (CSV)", criticalAlertsHeading: "نازک الرٹس — فوری کارروائی درکار",
    rescueOpsSubtitle: "ریسکیو آپریشنز بنائیں، تفویض کریں اور ٹریک کریں — خطرے کی ترجیح کے مطابق ترتیب دیا گیا۔",
    areasWord: "علاقے",
    rescue1122: "ریسکیو 1122", pdmaHelpline: "پی ڈی ایم اے پنجاب ہیلپ لائن",
    loginRequiredFull: "حکام کو تیز ردعمل میں مدد دینے والی تصدیق شدہ رپورٹس جمع کروانے کے لیے، براہ کرم اپنے شہری اکاؤنٹ سے لاگ ان کریں۔",
    incidentOverviewDesc: "کمیونٹی رپورٹس شیلٹرز، ہسپتالوں اور فعال ریسکیو آپریشنز کے ساتھ نقشے پر۔",
    exportCsv: "رپورٹ ایکسپورٹ کریں (CSV)", rescueOpsSubtitle: "ریسکیو آپریشنز بنائیں، تفویض کریں اور ٹریک کریں — خطرے کی ترجیح کے مطابق ترتیب دیا گیا۔",
    riverLevelNormal: "معمول — اپنے معمول کے کناروں کے اندر", riverLevelRising: "بڑھ رہا ہے — معمول سے نمایاں طور پر زیادہ",
    riverLevelOverflowing: "بہہ نکلا ہے — پانی کناروں سے باہر", riverLevelNotSure: "یقین نہیں / بتانا نہیں چاہتے",
    lowChart: "کم", medChart: "درمیانہ", highChart: "زیادہ", loginSuccessful: "لاگ ان کامیاب! ری ڈائریکٹ ہو رہا ہے...",
    mediumRiskAreas: "درمیانہ خطرے والے علاقے", elevatedDetected: "بلند — درمیانہ خطرے والے علاقے پائے گئے", criticalMultiple: "نازک — متعدد زیادہ خطرے والے علاقے",
    loginSuccessRedirect: "کامیابی سے لاگ ان ہو گئے! ڈیش بورڈ کی طرف بھیجا جا رہا ہے...",
  },
};

const LanguageContext = createContext({ lang: "en", t: (k) => k, toggleLang: () => {} });

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("appLang") || "en");

  useEffect(() => {
    localStorage.setItem("appLang", lang);
    document.documentElement.dir = lang === "ur" ? "rtl" : "ltr";
  }, [lang]);

  const toggleLang = () => setLang((prev) => (prev === "en" ? "ur" : "en"));
  const t = (key) => translations[lang][key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
